[workspace]
resolver = "2"
members = [
	"macro",
	"record",
	"crate/audio",
	"crate/messaging_interface",
	"interface/discord"
]

[workspace.dependencies]
# Logs
tracing = "0.1.43"
# Serilization/Deserilization
facet = "0.35.0"
facet-value = "0.35.0"
facet-format-json = "0.35.0"
facet-pretty = "0.35.0"
# Data structures
ringbuf = "0.4.8"
# Async
futures = "0.3.31"
async-trait = "0.1.89"
