[package]
name = "messaging_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
audio = { path = "../audio" }
async-trait = { workspace = true }
futures = { workspace = true }
thiserror = "2.0.17"
