[package]
name = "record"
version = "0.1.0"
edition = "2024"

[dependencies]
adaptors = { path = "../adaptors" }
iced = { version = "0.13.1",  features = ["image", "advanced", "lazy"] }
strum = { version = "0.27.1", features = ["derive"] }
futures = "0.3.31"
widgets = { path = "../widgets" }
cpal = "0.16.0"

tracing = "0.1.41"
tracing-subscriber = "0.3.20"

nom = "8.0.0"

ringbuf = "0.4.8"
rand = "0.9.2"
