[package]
name = "record"
version = "0.1.0"
edition = "2024"

[dependencies]
adaptors = { path = "../adaptors" }
iced = { version = "0.14.0",  features = ["image", "advanced", "lazy", "sipper"] }
strum = { version = "0.27.1", features = ["derive"] }
futures = "0.3.31"
widgets = { path = "../widgets" }

cpal = "0.16.0"

tracing = "0.1.41"
tracing-subscriber = "0.3.20"

# fontconfig = "0.10.0"
font-kit = "0.14.3"
nom = "8.0.0"

ringbuf = "0.4.8"
rand = "0.9.2"
